apiVersion: batch/v1
kind: Job
metadata:
  name: users-api-migrate-job
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: users-api-migrate-job
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: 
        command:
        - /bin/bash
        - /scripts/migrate.sh
        env:
        - name: DB_HOST
          value: cloud-sql-proxy-service
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials 
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials 
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials 
              key: db-password
