apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-sql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-sql-proxy
  template:
    metadata:
      labels:
        app: cloud-sql-proxy
    spec:
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.1
        args:
          - "--structured-logs"
          - "--port=5432"
          - "$(DB_CONNECTION_NAME)"
          - "--credentials-file=/secrets/service_account.json"
        ports:
        - containerPort: 5432
        env:
        - name: DB_CONNECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: cloud-sql-proxy-config
              key: connection-name
        volumeMounts:
        - name: secrets
          mountPath: "/secrets/"
          readOnly: true
        securityContext:
          runAsUser: 65532
      
      volumes:
      - name: secrets
        secret:
          secretName: cloud-sql-proxy-secrets