apiVersion: v1
kind: Service
metadata:
  name: users-api-manual-service
spec:
  selector:
    app: users-api
    type: auto
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: LoadBalancer