apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: users-api
      type: manual
  template:
    metadata:
      labels:
        app: users-api
        type: manual
    spec:
      containers:
      - name: users-api
        image: us-central1-docker.pkg.dev/modular-granite-374519/users-docker-repo/users-api:manual_1
        ports:
        - containerPort: 8000
        env:
        - name: JWT_SECRET_KEY
          value: secret
        - name: JWT_ALGORITHM
          value: HS256
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30"